steps:
  - name: 'hashicorp/terraform:light'
    id: 'validate-format'
    entrypoint: sh
    args:
      - -c
      - |
        cd dataplex_infra
        echo "🧪 Initializing Terraform"
        terraform init -backend-config="backend-prod.tfbackend"

        echo "🔍 Validating Terraform configuration"
        terraform validate

        echo "🧼 Checking Terraform formatting"
        if ! terraform fmt -check -diff -recursive; then
          echo ""
          echo "❌ Terraform files are not properly formatted, but we still allow checks to pass"
          echo "💡 Run 'terraform fmt' locally and push the changes."
        else
          echo "✅ Formatting looks good"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
