availableSecrets:
  secretManager:
    - versionName: projects/ferrous-cipher-432403-j0/secrets/github-token-terraform-dataplex-pr-comment/versions/latest
      env: 'GITHUB_TOKEN'

steps:
  - name: 'hashicorp/terraform:light'
    id: 'terraform-init-and-plan'
    entrypoint: sh
    args:
      - -c
      - |
        terraform init
        terraform plan -no-color > plan.txt

  - name: 'alpine'
    id: 'post-plan-to-github'
    entrypoint: sh
    env:
      - REPO_NAME=karsmars/terraform-dataplex-dq-test
    secretEnv: ['GITHUB_TOKEN']
    args:
      - -c
      - |
          apk add --no-cache curl jq
          if [ -z "$_PR_NUMBER" ]; then
            echo "❌ ERROR: Missing \$_PR_NUMBER"
            exit 1
          fi

          body=$(jq -Rs . < plan.txt)

          echo "Posting to https://api.github.com/repos/$REPO_NAME/issues/$_PR_NUMBER/comments"
          echo "GITHUB_TOKEN: ${GITHUB_TOKEN:0:11}..."

          curl -X POST \
            -H "Authorization: token $$GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\":$body}" \
            "https://api.github.com/repos/$REPO_NAME/pulls/$_PR_NUMBER/comments"

  - name: 'hashicorp/terraform:light'
    id: 'terraform-detailed-exit'
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -detailed-exitcode
        code=$?
        if [ $code -eq 1 ]; then
          echo "❌ terraform plan failed"
          exit 1
        elif [ $code -eq 2 ]; then
          echo "⚠️ terraform plan succeeded - changes detected" 
        else
          echo "✅ terraform plan succeeded"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
