steps:
  - name: 'hashicorp/terraform:light'
    entrypoint: sh
    args:
      - -c
      - |
        terraform init
        terraform plan -detailed-exitcode
        code=$?
        if [ $code -eq 1 ]; then
          echo "❌ terraform plan failed"
          exit 1
        elif [ $code -eq 2 ]; then
          echo "⚠️ terraform plan shows changes (expected for PRs)" 
        else
          echo "✅ No changes detected"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
