availableSecrets:
  secretManager:
    - versionName: projects/ferrous-cipher-432403-j0/secrets/github-token-terraform-dataplex-pr-comment/versions/latest
      env: GITHUB_TOKEN

steps:
  - name: 'hashicorp/terraform:light'
    entrypoint: sh
    env:
      - GITHUB_TOKEN
      - REPO_NAME=karsmars/terraform-dataplex-dq-test
      - PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER
    args:
      - -c
      - |
        terraform init

        terraform plan -no-color > plan.txt
        body=$(jq -Rs . < plan.txt)
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\":$body}" \
          "https://api.github.com/repos/$REPO_NAME/issues/$PULL_REQUEST_NUMBER/comments"

        terraform plan -detailed-exitcode
        code=$?
        if [ $code -eq 1 ]; then
          echo "❌ terraform plan failed"
          exit 1
        elif [ $code -eq 2 ]; then
          echo "⚠️ terraform plan succeeded - changes detected" 
        else
          echo "✅ terraform plan succeeded"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
